using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Schema;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using AgentForge.Data.Entities;

namespace AgentForge.Agents;

/// <summary>
/// The published, versioned contract of the supervisor↔worker interface (NFR-CONTRACT-W2-1): the
/// <see cref="HandoffEvent"/> every routing decision emits, and the <see cref="EvidenceAgentResult"/> the graph
/// accumulates across its workers and hands back. <see cref="RenderSchema"/> produces the JSON Schema
/// (<c>--export-graph-schema</c>), and <see cref="Serialize(HandoffEvent)"/> /
/// <see cref="Serialize(EvidenceAgentResult)"/> produce the wire form that schema describes. The evolution rules
/// - which change bumps which part of <see cref="Version"/> - are in ARCHITECTURE-DOCUMENTS.md §9.
/// </summary>
public static class EvidenceGraphContract
{
    /// <summary>
    /// The contract's semantic version. MAJOR for anything that can break a producer or a reader (a field
    /// removed, renamed, retyped or newly required, or a node added, renamed or removed); MINOR for an additive
    /// optional field; PATCH for a description-only change (ARCHITECTURE-DOCUMENTS.md §9).
    /// </summary>
    // 1.1.0 adds the brief's five citation fields as optional members of a document citation.
    public const string Version = "1.1.0";

    private static readonly JsonSerializerOptions WriteOptions = new() { WriteIndented = true, NewLine = "\n" };

    /// <summary>The contract's wire form of one handoff.</summary>
    /// <param name="handoff">A handoff the supervisor emitted.</param>
    /// <returns>Camel-cased JSON conforming to the schema's <c>HandoffEvent</c> definition.</returns>
    public static string Serialize(HandoffEvent handoff)
    {
        ArgumentNullException.ThrowIfNull(handoff);
        return JsonSerializer.Serialize(handoff, EvidenceGraphJsonContext.Default.HandoffEvent);
    }

    /// <summary>The contract's wire form of one run's result.</summary>
    /// <param name="result">The result the supervisor returned.</param>
    /// <returns>Camel-cased JSON conforming to the schema's <c>EvidenceAgentResult</c> definition.</returns>
    public static string Serialize(EvidenceAgentResult result)
    {
        ArgumentNullException.ThrowIfNull(result);
        return JsonSerializer.Serialize(result, EvidenceGraphJsonContext.Default.EvidenceAgentResult);
    }

    /// <summary>
    /// Renders the contract as a JSON Schema (draft 2020-12) document from the types themselves, so the
    /// committed file is produced rather than written. Every object is closed (<c>additionalProperties:
    /// false</c>) and a handoff's endpoints are enumerated from <see cref="EvidenceGraphNodes"/>.
    /// </summary>
    /// <returns>The schema document, indented with LF line endings and a trailing newline.</returns>
    public static string RenderSchema()
    {
        var exporterOptions = new JsonSchemaExporterOptions
        {
            TreatNullObliviousAsNonNullable = true,
            TransformSchemaNode = Close,
        };

        var document = new JsonObject
        {
            ["$schema"] = "https://json-schema.org/draft/2020-12/schema",
            ["$id"] = $"urn:agentforge:schema:evidence-graph:{Version}",
            ["title"] = "AgentForge evidence graph - supervisor/worker contract",
            ["version"] = Version,
            ["description"] =
                "Generated by scripts/generate-graph-schema.sh from AgentForge.Agents.EvidenceGraphContract; do not "
                + "edit by hand. ARCHITECTURE-DOCUMENTS.md section 9 carries the evolution rules.",
            ["$defs"] = new JsonObject
            {
                [nameof(HandoffEvent)] = EvidenceGraphJsonContext.Default.HandoffEvent.GetJsonSchemaAsNode(exporterOptions),
                [nameof(EvidenceAgentResult)] =
                    EvidenceGraphJsonContext.Default.EvidenceAgentResult.GetJsonSchemaAsNode(exporterOptions),
            },
        };

        return document.ToJsonString(WriteOptions) + "\n";
    }

    private static JsonNode Close(JsonSchemaExporterContext context, JsonNode schema)
    {
        if (schema is not JsonObject node)
        {
            return schema;
        }

        if (context.TypeInfo.Kind == JsonTypeInfoKind.Object && node.ContainsKey("properties"))
        {
            node["additionalProperties"] = false;
        }

        if (context.PropertyInfo is { } property
            && property.DeclaringType == typeof(HandoffEvent)
            && property.Name is "from" or "to")
        {
            node["enum"] = new JsonArray([.. EvidenceGraphNodes.All.Select(n => (JsonNode)n)]);
        }

        // A JsonConverter is opaque to the exporter and is not visited as its own node: sourceType arrives
        // already inlined as `{ "default": 1 }` (the ordinal). Rewrite it here, on the citation object, to
        // the brief's string tokens. Read off ToWireName so the schema cannot drift from the converter.
        if (context.TypeInfo.Type == typeof(DocumentCitation)
            && node["properties"] is JsonObject citationProperties
            && citationProperties["sourceType"] is JsonObject sourceType)
        {
            sourceType.Clear();
            sourceType["type"] = "string";
            sourceType["enum"] = new JsonArray(
                [.. Enum.GetValues<CitationSourceType>().Select(t => (JsonNode)CitationSourceTypeJson.ToWireName(t))]);
        }

        return node;
    }
}

/// <summary>
/// Source-generated serialization for the graph contract. Camel case, matching the HTTP projection of the
/// same records (<c>EvidenceResponsePayload</c>); constructor parameters and <c>required</c> members are
/// required, and nullable annotations are respected, so the rendered schema says what the types say.
/// </summary>
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    RespectNullableAnnotations = true,
    RespectRequiredConstructorParameters = true)]
[JsonSerializable(typeof(HandoffEvent))]
[JsonSerializable(typeof(EvidenceAgentResult))]
internal sealed partial class EvidenceGraphJsonContext : JsonSerializerContext;
